### ISSUE TITLE
Missing syntax highlighting for Python language

### ISSUE THREAD

**Issue by saisk8** [mrpbennett/atlantic-night-vscode-theme#2]
The theme does not highlight the methods of the Python language. It also does not highlight keywords like `const` in C. 

<img width="1440" alt="Screenshot of python code" src="https://user-images.githubusercontent.com/15904169/79047885-0ceb1580-7c37-11ea-886a-f29072ce575f.png">

**Comment by saisk8** [comment]
You probably missed `meta.function-call.generic.python` scope.

**Comment by mrpbennett** [comment]
Nice catch this has been fixed now, with commit https://github.com/mrpbennett/atlantic-night-vscode-theme/commit/5f6d17a82f0960d86ce74c2611b0891860b811c9 - let me know if the colour works.

**Comment by saisk8** [comment]
Nice! 

I don't think you have *published* an update yet. Until now, I have been using the `Blue` colour for methods. It would be interesting to try your change.

**Comment by mrpbennett** [comment]
Sorry...this is now built. I was on a new computer and didn't have all my VSC build tools working.

**Comment by saisk8** [comment]
The blue seems amazing.

**Comment by mrpbennett** [comment]
Glad you like it! 👍🏼
