### ISSUE TITLE
Bottom status bar stuck at purple

### ISSUE THREAD

**Issue by mqt0029** [mrpbennett/atlantic-night-vscode-theme#3]
Awesome theme!

But I could not figure out what caused the bottom bar to stay stuck in the default purple of VSCode.

OS: Ubuntu 20.04

VSCode version:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic

![Screenshot from 2020-06-09 22-46-59](https://user-images.githubusercontent.com/46615495/84224857-32639680-aaa3-11ea-9ab2-a5fd75bdb6c3.png)

**Comment by mrpbennett** [comment]
Thanks @mqt0029 what languages are you using with the theme, any general feedback?

I will look into the purple bar I know this does vanish actually when working on a file. I will take a look though.

**Comment by mqt0029** [comment]
@mrpbennett you are correct it does goes away when editing a file.

As for feedback, I am enjoying it, no complaints. It's very mute and easy on the eyes so it's fantastic! and I'm using it on multiple languages so I don't have any definitive feedback or ideas yet.

**Comment by Outi-s** [comment]
Did not want to open a separate issue for this, just have to say, I love this theme. Excellent Markdown syntax colors. Gave 5 ⭐s in the VS Code store. Keep up the good work and thank you for sharing it.

**Comment by mrpbennett** [comment]
Thanks @subi54 I have made a few updates to the JS syntax colouring will take a look at the bottom bar soon.

**Comment by mrpbennett** [comment]
@subi54 @mqt0029  this has now been fixed guys...thanks for your patience.
