### ISSUE TITLE
Icons of files are still same as before

### ISSUE THREAD

**Issue by faizansep5** [mrpbennett/atlantic-night-vscode-theme#6]
I installed this theme just because of those big icons that shows next to the filename but its not showing in my vs code...

**Comment by mrpbennett** [comment]
the file icons are from material icons https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons

**Comment by faizansep5** [comment]
Oh.. Thank you so much.. I was really wondering about that.. Btw thanks for
your awesome theme.. Ur theme and those icons combination is really
awesome!

**Comment by mrpbennett** [comment]
no worries, i am glad you like it. tell your friends 👯‍♀️
