### ISSUE TITLE
Syantax highlighting problems.

### ISSUE THREAD

**Issue by m4saurabh** [mrpbennett/atlantic-night-vscode-theme#7]
Hey thanks for creating this awesome theme. But I noticed it is highlighting typescript files incorrectly.

Here are few images for comparison.

![for](https://user-images.githubusercontent.com/79586784/120062134-2a1eb580-c07e-11eb-84cb-3e439275513b.JPG)

![Capture](https://user-images.githubusercontent.com/79586784/120062335-5129b700-c07f-11eb-9477-3ae267536574.JPG)

**Comment by mrpbennett** [comment]
Thanks for the nice words. The theme doesn't support typescript currently.

I'll work on this over the next week though. So keep an eye open for the next minor release. 🤪

**Comment by mrpbennett** [comment]
Hey @saurabhggc I believe this has now been fixed in version 3.3.0. 

Please let me know if you can update to 3.3.0 if not let me know

**Comment by m4saurabh** [comment]
# It is not working for `.tsx` files.

![s](https://user-images.githubusercontent.com/79586784/120421065-3dce6280-c383-11eb-854a-117bee95b2b3.JPG)

<img width="788" alt="ser" src="https://user-images.githubusercontent.com/79586784/120421132-59d20400-c383-11eb-8d63-10365edfded6.png">

**Comment by mrpbennett** [comment]
Should be good now, with 3.4.0 I only added `.ts` into 3.3.0 and not `.tsx` which is now in 3.4.0

Never used TypeScript before. Do let me know if you have any more issues, or notice anything else which is off. As I only used the examples you provided.

**Comment by m4saurabh** [comment]
Hey now the theme looks grate but the `gql` tags are not colorful at all. Here is a screenshot and a screenshot of the night owl theme for comprison.

<img width="377" alt="Screenshot 2021-06-03 105429" src="https://user-images.githubusercontent.com/79586784/120591752-4e9dd780-c45a-11eb-9ed0-0f5fead05eeb.png">

<img width="376" alt="compar" src="https://user-images.githubusercontent.com/79586784/120591757-52315e80-c45a-11eb-8d4e-b1f097f3bca6.png">

**Comment by mrpbennett** [comment]
Thanks can you keep adding faults you find. Here so I release the fixes in one release

So fixed is ts and tsx 

Needs to be fixed

GraphQL

**Comment by m4saurabh** [comment]
Well ok I will be happy doing that.
